umts/ft-forms

app/assets/stylesheets/application.css, app/assets/stylesheets/fields/edit.scss, app/assets/stylesheets/form_drafts/edit.scss, app/controllers/fields_controller.rb, app/models/field.rb, app/models/form_draft.rb, app/views/fields/edit.haml, app/views/form_drafts/edit.haml, app/views/layouts/application.haml, config/routes.rb, coverage/.last_run.json, spec/controllers/fields_controller_spec.rb
Closes #8.
Is a little clumsy:
+ requires a separate form
+ that form does some splitting and joining with newlines
+ the display isn't that great on the form editing page
=> Options interface

app/controllers/application_controller.rb, app/controllers/forms_controller.rb, app/controllers/sessions_controller.rb, app/models/user.rb, app/views/forms/show.haml, app/views/layouts/application.haml, app/views/sessions/dev_login.haml, config/routes.rb, coverage/.last_run.json, db/migrate/20150713162116_add_email_to_users.rb, db/schema.rb, spec/controllers/forms_controller_spec.rb, spec/controllers/sessions_controller_spec.rb, spec/factories/users.rb, spec/spec_helper.rb
Moving towards being prod-ready
=> Allow nil user

app/controllers/forms_controller.rb, spec/controllers/forms_controller_spec.rb
=> Implementing #deliver_now for mailers

app/assets/stylesheets/application.css, app/controllers/form_drafts_controller.rb, app/models/field.rb, app/models/form_draft.rb, app/views/form_drafts/edit.haml, app/views/form_drafts/show.haml, app/views/forms/show.haml, coverage/.last_run.json, db/migrate/20150722171806_add_placeholder_to_field.rb, db/schema.rb, spec/models/form_draft_spec.rb, spec/views/form_drafts/edit_spec.rb
=> Placeholders

app/controllers/forms_controller.rb, app/helpers/application_helper.rb, app/mailers/ft_forms_mailer.rb, app/models/field.rb, app/views/forms/show.haml, coverage/.last_run.json, db/migrate/20150801202941_add_email_to_forms.rb, db/migrate/20150802005823_add_email_to_form_drafts.rb, db/schema.rb, spec/controllers/forms_controller_spec.rb, spec/factories/forms.rb, spec/mailers/ft_forms_mailer_spec.rb, spec/models/field_spec.rb
=> Unique names

Capfile, Gemfile, Gemfile.lock, config/deploy/production.rb
This fixes the "only @dfaulken can deploy" problem (also does some other Capistrano tweaking).
=> Cap adjustments

spec/models/form_spec.rb
=> changed model testing to reflect reality

spec/mailers/ft_forms_mailer_spec.rb
=> wrote tests to add comma separated email addresses.

app/assets/stylesheets/form_drafts/edit.scss, app/views/form_drafts/edit.haml, spec/models/form_spec.rb, spec/views/form_drafts/edit_spec.rb, spec/views/layouts/application_spec.rb
Form-within-a-form problem fixed by using flexboxes in CSS instead of tables. Changed specs so tests pass. 
resolves #27
=> Flexbox drafts edit

app/helpers/application_helper.rb, app/models/field.rb, app/views/forms/show.haml, app/views/ft_forms_mailer/send_form.text.erb, coverage/.last_run.json, spec/helpers/application_helper_spec.rb, spec/models/field_spec.rb, spec/views/ft_forms_mailer/send_form_spec.rb
closes #46 
Now it looks like this in the mailer view:
So pretty!
=> Mailer view editing

README.md
=> Add CodeClimate issue count badge to README

spec/controllers/fields_controller_spec.rb, spec/controllers/forms_controller_spec.rb, spec/spec_helper.rb, spec/support/redirect_back_matcher.rb
In the spirit of umts/jobapps#130.
=> Add custom RSpec matcher for requests that redirect back

app/views/layouts/_footer.haml, spec/views/layouts/footer_spec.rb
=> Use mailto link in footer

Gemfile, Gemfile.lock, app/controllers/forms_controller.rb, app/mailers/ft_forms_mailer.rb, app/views/ft_forms_mailer/send_form.text.erb, coverage/.last_run.json, spec/controllers/forms_controller_spec.rb, spec/mailers/ft_forms_mailer_spec.rb, spec/views/ft_forms_mailer/send_form_spec.rb
Did we just... did we forget about this
=> Add requesting user to email

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/vendor_invocations.js.coffee, app/assets/stylesheets/application.css, vendor/assets/javascripts/jquery.datetimepicker.full.js, vendor/assets/stylesheets/jquery.datetimepicker.css
Fixes the "sometimes the year goes back to 1899" problem.
=> use files from vendor instead, and use moment as dateparser

db/migrate/20150611193935_create_forms.rb, db/migrate/20150611195030_create_fields.rb, db/migrate/20150612174601_add_required_to_fields.rb, db/migrate/20150615184157_add_options_to_fields.rb, db/migrate/20150622181855_create_users.rb, db/migrate/20150629192848_create_form_drafts.rb, db/migrate/20150629200647_add_form_draft_id_to_fields.rb, db/migrate/20150629200910_add_user_id_to_form_drafts.rb, db/migrate/20150713162116_add_email_to_users.rb, db/migrate/20150722171806_add_placeholder_to_field.rb, db/migrate/20150801202941_add_email_to_forms.rb, db/migrate/20150802005823_add_email_to_form_drafts.rb, db/migrate/20151204164825_add_replyto_to_form_drafts.rb, db/migrate/20151204165537_add_replyto_to_forms.rb, db/migrate/20170414155904_add_slug_to_forms.rb, db/schema.rb
Ordinarily, I'd be like, "who cares?" but there's a pending migration that won't run in production without this.
Dunno why the schema file got all changey.
=> Added migration versions.

spec/rails_helper.rb, spec/views/fields/edit_spec.rb, spec/views/form_drafts/edit_spec.rb, spec/views/form_drafts/show_spec.rb, spec/views/forms/index_spec.rb, spec/views/forms/show_spec.rb, spec/views/forms/thank_you_spec.rb, spec/views/ft_forms_mailer/send_confirmation_text_spec.rb, spec/views/ft_forms_mailer/send_form_spec.rb, spec/views/layouts/application_spec.rb, spec/views/layouts/footer_spec.rb, spec/views/layouts/umass_search_spec.rb, spec/views/sessions/dev_login_spec.rb
=> Just include those helpers in the config

.codeclimate.yml, .haml-lint.yml, app/assets/stylesheets/application.scss, app/assets/stylesheets/fields/edit.scss, app/assets/stylesheets/form_drafts/edit.scss, app/assets/stylesheets/forms/index.scss, app/assets/stylesheets/forms/show.scss, app/assets/stylesheets/umass.scss, app/views/form_drafts/edit.haml, app/views/form_drafts/show.haml, app/views/forms/_form.haml, app/views/forms/index.haml, app/views/forms/new.haml, app/views/forms/show.haml, app/views/layouts/_umass_search.haml, app/views/layouts/application.haml, app/views/sessions/dev_login.haml, spec/system/forms_index_spec.rb, spec/views/form_drafts/show_spec.rb, spec/views/forms/index_spec.rb, spec/views/layouts/application_spec.rb, spec/views/layouts/umass_search_spec.rb
No reason not to do this. 
closes #95
=> Lint that haml

app/assets/javascripts/vendor_invocations.js.coffee
=> datepicker needs format specified

yarn.lock
Primarily to bump jquery to 3.5.0
=> Yarn update

app/controllers/application_controller.rb, config/initializers/new_framework_defaults_5_1.rb, config/initializers/new_framework_defaults_5_2.rb
I think it's safe to switch on all of these at this point.
=> Flip on Rails 5.2 defaults

config/initializers/content_security_policy.rb
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
=> Enable CSP

config/deploy.rb
(Wonder how many times I screwed this up)
=> It's _Passenger_ we're restarting

db/migrate/20210308165232_add_unique_indexes.rb, db/migrate/20210308170840_add_some_other_indexes.rb, db/migrate/20210308171305_add_default_to_user_staff.rb, db/schema.rb
Added the `unique` indexes that Rubocop/Rails recommended, plus one other.
Also added a default value to one boolean field.
=> Added indexes to several tables

.rubocop.yml, app/controllers/application_controller.rb, app/controllers/form_drafts_controller.rb, app/controllers/forms_controller.rb, app/helpers/application_helper.rb, app/mailers/ft_forms_mailer.rb, app/models/form.rb, config/deploy.rb, config/deploy/production.rb, config/routes.rb, db/seeds.rb, lib/form_data_parser.rb, spec/helpers/application_helper_spec.rb, spec/lib/form_data_parser_spec.rb
I removed nearly all of the... opinions from the `.rubocop.yml` file and refactored the 3 or 4 violations.
=> Rubocop adjustments
